/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export type { AuthControllerRegister$Params as AuthControllerRegister$Params } from './fn/auth/auth-controller-register';
export { authControllerRegister as authControllerRegister } from './fn/auth/auth-controller-register';
export type { AuthControllerLogin$Params as AuthControllerLogin$Params } from './fn/auth/auth-controller-login';
export { authControllerLogin as authControllerLogin } from './fn/auth/auth-controller-login';
export type { AuthControllerLogout$Params as AuthControllerLogout$Params } from './fn/auth/auth-controller-logout';
export { authControllerLogout as authControllerLogout } from './fn/auth/auth-controller-logout';
export type { AuthControllerRefresh$Params as AuthControllerRefresh$Params } from './fn/auth/auth-controller-refresh';
export { authControllerRefresh as authControllerRefresh } from './fn/auth/auth-controller-refresh';
export type { AuthHealthControllerHealthz$Params as AuthHealthControllerHealthz$Params } from './fn/health/auth-health-controller-healthz';
export { authHealthControllerHealthz as authHealthControllerHealthz } from './fn/health/auth-health-controller-healthz';
