export const ICONS_CONSTANTS = {
  APP: {
    LOGO: 'brand-bookmark-animated',
    BOOKMARK: 'brand-bookmark',
    BOOKMARK_ANIMATED: 'brand-bookmark-animated',
    BOOKMARK_S: 'brand-bookmark-s',
    BOOKMARK_S_MIN: 'brand-bookmark-s-min',
    BOOKMARK_ANIMATED_S: 'brand-bookmark-animated-s',
    BOOKMARK_OUTLINE: 'brand-bookmark-outline',
    BOOKMARK_OUTLINE_S: 'brand-bookmark-outline-s',
    BOOKMARK_OUTLINE_ANIMATED: 'brand-bookmark-outline-animated',
    BOOKMARK_OUTLINE_ANIMATED_S: 'brand-bookmark-outline-animated-s',
  },
  AUTH: {
    EMAIL: 'email',
    PASSWORD: 'lock',
    USER: 'person',
    LOGIN_BUTTON: 'auth-login-button',
    LOGOUT_BUTTON: 'auth-logout-button',
    USER_SIDEBAR: 'auth-user-sidebar',
    EMAIL_INPUT: 'auth-email-input',
    PASSWORD_INPUT: 'auth-password-input',
    VISIBILITY_INPUT: 'auth-visibility-on',
    VISIBILITY_OFF_INPUT: 'auth-visibility-off',
    VISIBILITY: 'visibility',
    VISIBILITY_OFF: 'visibility_off',
  },
  NAV: {
    NOTIFICATIONS: 'notifications',
    ACCOUNT: 'account_circle',
  },
  TREE: {
    EXPANDED: 'expand_more',
    COLLAPSED: 'chevron_right',
  },
  NOTIFICATION: {
    SUCCESS: 'check_circle',
    ERROR: 'error',
    WARNING: 'warning',
    INFO: 'info',
    CLOSE: 'close',
  },
  DASHBOARD: {
    CODE: 'code',
    HTML: 'html',
    SCRIPT: 'script',
    REBASE_EDIT: 'rebase_edit',
    PALETTE: 'palette',
    DRAW: 'draw',
    GRID_VIEW: 'grid_view',
    RESTAURANT: 'restaurant',
    FLIGHT: 'flight',
  },
} as const;
