export const ICONS_CONSTANTS = {
  APP: {
    LOGO: 'rocket_launch',
  },
  AUTH: {
    EMAIL: 'email',
    PASSWORD: 'lock',
    USER: 'person',
    LOGIN_BUTTON: 'auth-login-button',
    LOGOUT_BUTTON: 'auth-logout-button',
    USER_SIDEBAR: 'auth-user-sidebar',
    EMAIL_INPUT: 'auth-email-input',
    PASSWORD_INPUT: 'auth-password-input',
    VISIBILITY_INPUT: 'auth-visibility-on',
    VISIBILITY_OFF_INPUT: 'auth-visibility-off',
    VISIBILITY: 'visibility',
    VISIBILITY_OFF: 'visibility_off',
  },
  NAV: {
    NOTIFICATIONS: 'notifications',
    ACCOUNT: 'account_circle',
  },
  TREE: {
    EXPANDED: 'expand_more',
    COLLAPSED: 'chevron_right',
  },
  NOTIFICATION: {
    SUCCESS: 'check_circle',
    ERROR: 'error',
    WARNING: 'warning',
    INFO: 'info',
    CLOSE: 'close',
  },
  DASHBOARD: {
    CODE: 'code',
    HTML: 'html',
    SCRIPT: 'script',
    REBASE_EDIT: 'rebase_edit',
    PALETTE: 'palette',
    DRAW: 'draw',
    GRID_VIEW: 'grid_view',
    RESTAURANT: 'restaurant',
    FLIGHT: 'flight',
  },
} as const;
