/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseWrapper } from '../../models/api-response-wrapper';

export interface LinksControllerDeleteLink$Params {

/**
 * Link ID
 */
  id: number;
}

export function linksControllerDeleteLink(http: HttpClient, rootUrl: string, params: LinksControllerDeleteLink$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseWrapper>> {
  const rb = new RequestBuilder(rootUrl, linksControllerDeleteLink.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseWrapper>;
    })
  );
}

linksControllerDeleteLink.PATH = '/links/{id}';
