/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseWrapper } from '../../models/api-response-wrapper';
import { MarkLinksAsFavoriteRequest } from '../../models/mark-links-as-favorite-request';

export interface LinksControllerMarkLinksAsFavorite$Params {
      body: MarkLinksAsFavoriteRequest
}

export function linksControllerMarkLinksAsFavorite(http: HttpClient, rootUrl: string, params: LinksControllerMarkLinksAsFavorite$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseWrapper>> {
  const rb = new RequestBuilder(rootUrl, linksControllerMarkLinksAsFavorite.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseWrapper>;
    })
  );
}

linksControllerMarkLinksAsFavorite.PATH = '/links/favorite';
