import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const API_DIR = 'src/api';
const TS_NOCHECK = '// @ts-nocheck';
const GENERATED_MARKER = '/* Code generated by ng-openapi-gen DO NOT EDIT. */';

async function getFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await getFiles(fullPath)));
    } else if (entry.name.endsWith('.ts')) {
      files.push(fullPath);
    }
  }

  return files;
}

async function addTsNocheck(filePath) {
  const content = await readFile(filePath, 'utf-8');

  if (!content.includes(GENERATED_MARKER)) return;
  if (content.includes(TS_NOCHECK)) return;

  const updated = content.replace(GENERATED_MARKER, `${GENERATED_MARKER}\n${TS_NOCHECK}`);
  await writeFile(filePath, updated, 'utf-8');
}

const files = await getFiles(API_DIR);
await Promise.all(files.map(addTsNocheck));

console.log(`api-postgen: added ${TS_NOCHECK} to ${files.length} generated files`);
