/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export type { LinksControllerCreateLink$Params as LinksControllerCreateLink$Params } from './fn/links/links-controller-create-link';
export { linksControllerCreateLink as linksControllerCreateLink } from './fn/links/links-controller-create-link';
export type { LinksControllerGetLinkById$Params as LinksControllerGetLinkById$Params } from './fn/links/links-controller-get-link-by-id';
export { linksControllerGetLinkById as linksControllerGetLinkById } from './fn/links/links-controller-get-link-by-id';
export type { LinksControllerDeleteLink$Params as LinksControllerDeleteLink$Params } from './fn/links/links-controller-delete-link';
export { linksControllerDeleteLink as linksControllerDeleteLink } from './fn/links/links-controller-delete-link';
export type { LinksControllerUpdateLink$Params as LinksControllerUpdateLink$Params } from './fn/links/links-controller-update-link';
export { linksControllerUpdateLink as linksControllerUpdateLink } from './fn/links/links-controller-update-link';
export type { LinksControllerGetLinksPaginated$Params as LinksControllerGetLinksPaginated$Params } from './fn/links/links-controller-get-links-paginated';
export { linksControllerGetLinksPaginated as linksControllerGetLinksPaginated } from './fn/links/links-controller-get-links-paginated';
export type { LinksControllerMarkLinksAsFavorite$Params as LinksControllerMarkLinksAsFavorite$Params } from './fn/links/links-controller-mark-links-as-favorite';
export { linksControllerMarkLinksAsFavorite as linksControllerMarkLinksAsFavorite } from './fn/links/links-controller-mark-links-as-favorite';
export type { LinksControllerUnmarkLinksAsFavorite$Params as LinksControllerUnmarkLinksAsFavorite$Params } from './fn/links/links-controller-unmark-links-as-favorite';
export { linksControllerUnmarkLinksAsFavorite as linksControllerUnmarkLinksAsFavorite } from './fn/links/links-controller-unmark-links-as-favorite';
export type { GroupLinksControllerCreateGroupLink$Params as GroupLinksControllerCreateGroupLink$Params } from './fn/group-links/group-links-controller-create-group-link';
export { groupLinksControllerCreateGroupLink as groupLinksControllerCreateGroupLink } from './fn/group-links/group-links-controller-create-group-link';
export type { GroupLinksControllerGetGroupLinksPaginated$Params as GroupLinksControllerGetGroupLinksPaginated$Params } from './fn/group-links/group-links-controller-get-group-links-paginated';
export { groupLinksControllerGetGroupLinksPaginated as groupLinksControllerGetGroupLinksPaginated } from './fn/group-links/group-links-controller-get-group-links-paginated';
export type { GroupLinksControllerMarkGroupLinksAsFavorite$Params as GroupLinksControllerMarkGroupLinksAsFavorite$Params } from './fn/group-links/group-links-controller-mark-group-links-as-favorite';
export { groupLinksControllerMarkGroupLinksAsFavorite as groupLinksControllerMarkGroupLinksAsFavorite } from './fn/group-links/group-links-controller-mark-group-links-as-favorite';
export type { GroupLinksControllerUnmarkGroupLinksAsFavorite$Params as GroupLinksControllerUnmarkGroupLinksAsFavorite$Params } from './fn/group-links/group-links-controller-unmark-group-links-as-favorite';
export { groupLinksControllerUnmarkGroupLinksAsFavorite as groupLinksControllerUnmarkGroupLinksAsFavorite } from './fn/group-links/group-links-controller-unmark-group-links-as-favorite';
export type { GroupLinksControllerGetGroupLinkById$Params as GroupLinksControllerGetGroupLinkById$Params } from './fn/group-links/group-links-controller-get-group-link-by-id';
export { groupLinksControllerGetGroupLinkById as groupLinksControllerGetGroupLinkById } from './fn/group-links/group-links-controller-get-group-link-by-id';
export type { GroupLinksControllerDeleteGroupLink$Params as GroupLinksControllerDeleteGroupLink$Params } from './fn/group-links/group-links-controller-delete-group-link';
export { groupLinksControllerDeleteGroupLink as groupLinksControllerDeleteGroupLink } from './fn/group-links/group-links-controller-delete-group-link';
export type { GroupLinksControllerUpdateGroupLink$Params as GroupLinksControllerUpdateGroupLink$Params } from './fn/group-links/group-links-controller-update-group-link';
export { groupLinksControllerUpdateGroupLink as groupLinksControllerUpdateGroupLink } from './fn/group-links/group-links-controller-update-group-link';
export type { LinksHealthControllerHealthz$Params as LinksHealthControllerHealthz$Params } from './fn/health/links-health-controller-healthz';
export { linksHealthControllerHealthz as linksHealthControllerHealthz } from './fn/health/links-health-controller-healthz';
