/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export type { ApiNullResponse } from './models/api-null-response';
export type { ApiResponseMessageModel } from './models/api-response-message-model';
export type { ApiResponseWrapper } from './models/api-response-wrapper';
export type { CreateGroupLinkRequest } from './models/create-group-link-request';
export type { CreateLinkRequest } from './models/create-link-request';
export type { EApiResponseMessageType } from './models/e-api-response-message-type';
export type { EPaginatedOrder } from './models/e-paginated-order';
export type { GetGroupLinkByIdResponse } from './models/get-group-link-by-id-response';
export type { GetLinkByIdResponse } from './models/get-link-by-id-response';
export type { GroupLinkBasicResponse } from './models/group-link-basic-response';
export type { LinkBasicResponse } from './models/link-basic-response';
export type { LinkLastStatusCode } from './models/link-last-status-code';
export type { MarkGroupLinksAsFavoriteRequest } from './models/mark-group-links-as-favorite-request';
export type { MarkLinksAsFavoriteRequest } from './models/mark-links-as-favorite-request';
export type { PaginatedRequest } from './models/paginated-request';
export type { PaginatedResponseForModel } from './models/paginated-response-for-model';
export type { RgbColorDto } from './models/rgb-color-dto';
export type { SuccessFailureResponse } from './models/success-failure-response';
export type { UnmarkGroupLinksAsFavoriteRequest } from './models/unmark-group-links-as-favorite-request';
export type { UnmarkLinksAsFavoriteRequest } from './models/unmark-links-as-favorite-request';
export type { UpdateGroupLinkRequest } from './models/update-group-link-request';
export type { UpdateLinkRequest } from './models/update-link-request';
