/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { EApiResponseMessageType } from '../models/e-api-response-message-type';
export interface ApiResponseMessageModel {
  message: string;
  type: EApiResponseMessageType;
}
