/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { ApiResponseMessageModel } from '../models/api-response-message-model';
import { LoginResponse } from '../models/login-response';
export interface ApiResponseWrapper {
  code?: string;
  data: LoginResponse;
  messageList?: Array<ApiResponseMessageModel>;
  success: boolean;
}
