/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export interface LoginRequest {

  /**
   * User email address
   */
  email: string;

  /**
   * User password
   */
  password: string;
}
