/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { EPaginatedOrder } from '../models/e-paginated-order';
export interface PaginatedRequest {

  /**
   * Current page number
   */
  currentPage?: number;

  /**
   * Number of items to skip
   */
  skip?: number;

  /**
   * Field name to sort by
   */
  sortBy?: string;

  /**
   * Sort direction
   */
  sortOrder?: EPaginatedOrder;

  /**
   * Number of items per page
   */
  take?: number;
}
