/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export interface ApiResponseMessageModel {
  message: string;
  type: 'info' | 'success' | 'warning' | 'error' | 'critical';
}
