/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { ApiResponseMessageModel } from '../models/api-response-message-model';
export interface ApiNullResponse {
  code?: string;
  data: null;
  messageList?: Array<ApiResponseMessageModel>;
  success: boolean;
}
