/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { ApiResponseMessageModel } from '../models/api-response-message-model';
import { GetGroupLinkByIdResponse } from '../models/get-group-link-by-id-response';
export interface ApiResponseWrapper {
  code?: string;
  data: GetGroupLinkByIdResponse;
  messageList?: Array<ApiResponseMessageModel>;
  success: boolean;
}
