/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { RgbColorDto } from '../models/rgb-color-dto';
export interface CreateGroupLinkRequest {

  /**
   * RGB color object { r, g, b }
   */
  color?: RgbColorDto;

  /**
   * Group link description
   */
  description?: string;

  /**
   * Icon identifier
   */
  icon?: string;

  /**
   * Whether the group is marked as favorite
   */
  isFavorite?: boolean;

  /**
   * Parent group link ID
   */
  parentGroupLinkId?: number | null;

  /**
   * Group link title
   */
  title: string;
}
