/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { EApiResponseMessageType } from './e-api-response-message-type';

/**
 * Each possible value of `EApiResponseMessageType`
 */
export const E_API_RESPONSE_MESSAGE_TYPE: EApiResponseMessageType[] = [
  'info',
  'success',
  'warning',
  'error',
  'critical'
];