/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { EPaginatedOrder } from './e-paginated-order';

/**
 * Each possible value of `EPaginatedOrder`
 */
export const E_PAGINATED_ORDER: EPaginatedOrder[] = [
  'ASC',
  'DESC'
];