/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { GroupLinkBasicResponse } from '../models/group-link-basic-response';
export interface GetLinkByIdResponse {
  description?: {
};
  faviconUrl?: {
};
  groupLink?: GroupLinkBasicResponse | null;
  groupLinkId?: number | null;
  id: number;
  imagePreviewUrl?: {
};
  isActive: boolean;
  isFavorite: boolean;
  lastCheckedAt?: string;
  lastStatusCode: 0 | 200 | 201 | 202 | 204 | 400 | 401 | 403 | 404 | 500 | 503 | 520;
  lastVisitedAt?: string;
  normalizedUrl?: string;
  tagList?: Array<string>;
  title?: {
};
  url: string;
}
