/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { LinkBasicResponse } from '../models/link-basic-response';
export interface GetGroupLinkByIdResponse {

  /**
   * RGB color object { r, g, b }
   */
  color?: {
} | null;
  description?: {
} | null;
  icon?: {
} | null;
  id: number;
  isFavorite: boolean;
  links?: Array<LinkBasicResponse> | null;
  parentGroupLinkId?: number | null;
  title: string;
}
