/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export interface GroupLinkBasicResponse {

  /**
   * RGB color object { r, g, b }
   */
  color?: {
} | null;
  icon?: {
} | null;
  id: number;
  title: string;
}
