/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export interface LinkBasicResponse {
  faviconUrl?: {
};
  id: number;
  isActive: boolean;
  isFavorite: boolean;
  lastStatusCode: 0 | 200 | 201 | 202 | 204 | 400 | 401 | 403 | 404 | 500 | 503 | 520;
  title?: {
};
  url: string;
}
