/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { LinkLastStatusCode } from '../models/link-last-status-code';
export interface LinkBasicResponse {
  faviconUrl?: {
};
  id: number;
  isActive: boolean;
  isFavorite: boolean;
  lastStatusCode: LinkLastStatusCode;
  title?: {
};
  url: string;
}
