/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { LinkLastStatusCode } from './link-last-status-code';

/**
 * Each possible value of `LinkLastStatusCode`
 */
export const LINK_LAST_STATUS_CODE: LinkLastStatusCode[] = [
  0,
  200,
  201,
  202,
  204,
  400,
  401,
  403,
  404,
  500,
  503,
  520
];