/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export interface MarkGroupLinksAsFavoriteRequest {

  /**
   * List of group link IDs to mark as favorite
   */
  groupLinkIdList: Array<number>;
}
