/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { GetLinkByIdResponse } from '../models/get-link-by-id-response';
export interface PaginatedResponseForModel {
  currentPage?: number;
  filters?: {
};
  items: Array<GetLinkByIdResponse>;
  nextPage?: number;
  previousPage?: number;
  skip?: number;
  sortBy?: string;
  sortOrder?: string;
  take: number;
  total: number;
}
