/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export interface PaginatedRequest {

  /**
   * Current page number
   */
  currentPage?: number;

  /**
   * Number of items to skip
   */
  skip?: number;

  /**
   * Field name to sort by
   */
  sortBy?: string;

  /**
   * Sort direction
   */
  sortOrder?: 'ASC' | 'DESC';

  /**
   * Number of items per page
   */
  take?: number;
}
