/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export interface RgbColorDto {

  /**
   * Blue component (0-255)
   */
  b: number;

  /**
   * Green component (0-255)
   */
  g: number;

  /**
   * Red component (0-255)
   */
  r: number;
}
