/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export interface SuccessFailureResponse {

  /**
   * List of items that failed to process
   */
  failureList: Array<Array<any>>;

  /**
   * List of successfully processed items
   */
  successList: Array<Array<any>>;
}
