/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export interface UnmarkGroupLinksAsFavoriteRequest {

  /**
   * List of group link IDs to unmark as favorite
   */
  groupLinkIdList: Array<number>;
}
