/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export interface UnmarkLinksAsFavoriteRequest {

  /**
   * List of link IDs to mark as favorite
   */
  linkIdList: Array<number>;
}
