/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

import { RgbColorDto } from '../models/rgb-color-dto';
export interface UpdateGroupLinkRequest {

  /**
   * RGB color object { r, g, b }
   */
  color?: RgbColorDto;

  /**
   * Group link description
   */
  description?: {
};

  /**
   * Icon identifier
   */
  icon?: {
};

  /**
   * Whether the group is marked as favorite
   */
  isFavorite?: boolean;

  /**
   * Parent group link ID (null to remove from parent)
   */
  parentGroupLinkId?: number | null;

  /**
   * Group link title
   */
  title?: string;
}
