/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
// @ts-nocheck

export interface UpdateLinkRequest {

  /**
   * Link description
   */
  description?: string;

  /**
   * Group link ID to assign this link to (null to remove from group)
   */
  groupLinkId?: number | null;

  /**
   * Whether the link is marked as favorite
   */
  isFavorite?: boolean;

  /**
   * List of tags associated with the link
   */
  tagList?: Array<string>;

  /**
   * Link title
   */
  title?: string;

  /**
   * Link URL
   */
  url?: string;
}
